spring.application.name=disaster-alert-backend

# =========================================================
# SERVER
# =========================================================

server.port=${PORT:8080}
server.address=0.0.0.0


# =========================================================
# MYSQL DATABASE - AIVEN
# =========================================================

spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=true&requireSSL=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


# =========================================================
# JPA / HIBERNATE
# =========================================================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true


# =========================================================
# DATABASE INITIALIZATION
# =========================================================

spring.sql.init.mode=always
spring.sql.init.continue-on-error=false


# =========================================================
# JWT
# =========================================================

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}


# =========================================================
# CORS
# =========================================================

app.cors.origins=${CORS_ORIGINS:http://localhost:5173}


# =========================================================
# OTP
# =========================================================

app.otp.provider=${OTP_PROVIDER:console}


# =========================================================
# SMS
# =========================================================

app.sms.enabled=${SMS_ENABLED:false}


# =========================================================
# FIREBASE FCM
# =========================================================

app.fcm.enabled=${FCM_ENABLED:true}
app.fcm.project-id=${FIREBASE_PROJECT_ID:natural-disaster-alert-38cb7}


# =========================================================
# REAL GOVERNMENT CAP SOURCE - NDMA SACHET
# =========================================================

app.cap.ndma-rss-url=${NDMA_CAP_RSS_URL:https://sachet.ndma.gov.in/cap_public_website/rss/rss_india.xml}

app.cap.poll-ms=${CAP_POLL_MS:300000}

app.cap.initial-delay-ms=${CAP_INITIAL_DELAY_MS:15000}